name: Ejercicio 2
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar requirements.txt
        run: pip install -r requirements.txt

      - name: Ejecutar pytest
        run: pytest